DEFAULT_ERROR_STATUS = 400

CODE_HTTP_STATUS = {
    "VALIDATION_ERROR": 400,
    "INVALID_FILE": 400,
    "MISSING_COLUMN": 400,
    "AUTHENTICATION_FAILED": 401,
    "PERMISSION_DENIED": 403,
    "NOT_FOUND": 404,
    "FILE_NOT_FOUND": 404,
    "INTERNAL_ERROR": 500,
}
