import type { Scenario } from '../scenarios';

const MAIL = 'MX-MAIL';
const VPN = 'MX-VPN';

export const PEOPLE: Scenario[] = [
  {
    id: 'S10',
    title: 'operator · not offered to raise a request: no New request in the list, the dashboard or a person\'s menu',
    asker: 'operator',
    people: [],
    acts: [],
    send: 'now',
    refusals: [{ refusal: 'not-offered', people: [{ kind: 'bare', at: 10 }] }],
  },
  {
    id: 'S11',
    title: 'manager · one existing person · add a User service, username given by the customer · not modified · accepted by group · one row on the pre-filled date · recap by action',
    asker: 'manager',
    people: [{ existing: [{ kind: 'named', at: 0 }] }],
    acts: [{ service: MAIL, op: 'Add', scope: 'all' }],
    send: 'now',
    decisions: [{ accept: 'groups' }],
    execute: [{ row: { act: { service: MAIL, op: 'Add', scope: 'all' }, target: { kind: 'named', at: 0 } } }],
    recap: 'By action',
    complete: true,
    customerReads: true,
    outcome: {
      status: 'Completed',
      lines: 1,
      accepted: 1,
      rejected: 0,
      people: [{ who: { kind: 'named', at: 0 }, services: [{ service: MAIL, status: 'Active', start: 0 }] }],
    },
  },
  {
    id: 'S12',
    title: 'manager · a future person, full details · add with username given, a past requested date not offered, asked for a future date · date changed then an act added · locked once work starts · accepted line by line · created from their own view · recap by person',
    asker: 'manager',
    people: [
      {
        future: {
          key: 'fd',
          label: 'Full Details',
          department: 'alpha',
          email: 'zze2e.mx.s12@example.invalid',
          username: 'zze2e.mx.s12',
        },
      },
    ],
    acts: [{ service: MAIL, op: 'Add', scope: 'all' }],
    requestedDate: 6,
    refusedRequestedDate: -6,
    send: 'now',
    sentLines: 1,
    modifications: [
      { changes: [{ date: 10 }], lines: 1 },
      { changes: [{ addAct: { service: VPN, op: 'Add', scope: 'all' } }] },
    ],
    lockedAfterStart: true,
    decisions: [{ accept: 'lines' }],
    prepare: [{ person: 'fd', how: 'create', opensOn: 'Create new', ownView: true }],
    execute: [{ person: { future: 'fd' } }],
    recap: 'By person',
    complete: true,
    customerReads: true,
    outcome: {
      status: 'Completed',
      lines: 2,
      accepted: 2,
      rejected: 0,
      people: [
        {
          who: { future: 'fd' },
          services: [
            { service: MAIL, status: 'Active', start: 10 },
            { service: VPN, status: 'Active', start: 10 },
          ],
          username: 'zze2e.mx.s12',
          department: 'alpha',
        },
      ],
    },
  },
  {
    id: 'S13',
    title: 'manager · a future person, name only, with an existing one · add, no username · the existing one removed · not offered to edit to the operator · created · username on its own row · Execute N ready',
    asker: 'manager',
    people: [{ future: { key: 'nm', label: 'Name Only' } }, { existing: [{ kind: 'bare', at: 11 }] }],
    acts: [{ service: MAIL, op: 'Add', scope: 'all' }],
    send: 'now',
    sentLines: 2,
    notOfferedTo: 'operator',
    modifications: [{ changes: [{ removePerson: { kind: 'bare', at: 11 } }] }],
    decisions: [{ accept: 'groups' }],
    prepare: [{ person: 'nm', how: 'create', department: 'beta' }],
    usernames: { rows: [{ future: 'nm' }] },
    execute: [{ ready: true }],
    complete: true,
    outcome: {
      status: 'Completed',
      lines: 1,
      accepted: 1,
      rejected: 0,
      people: [
        { who: { future: 'nm' }, services: [{ service: MAIL, status: 'Active', start: 0 }], department: 'beta' },
        { who: { kind: 'bare', at: 11 }, services: [] },
      ],
    },
  },
  {
    id: 'S14',
    title: 'manager · the same add on several existing people, no username · a person added · one line refused · usernames in one dialog · the group button on a changed date · completes saying what was refused',
    asker: 'manager',
    people: [{ existing: [{ kind: 'bare', at: 12 }, { kind: 'bare', at: 13 }] }],
    acts: [{ service: MAIL, op: 'Add', scope: 'all' }],
    send: 'now',
    sentLines: 2,
    modifications: [
      {
        changes: [
          { addPeople: { existing: [{ kind: 'bare', at: 14 }] } },
          { removeAct: { service: MAIL, op: 'Add', scope: 'all' } },
          { addAct: { service: MAIL, op: 'Add', scope: 'all' } },
        ],
      },
    ],
    decisions: [
      { refuseLine: { kind: 'bare', at: 13 }, reason: 'ZZE2E matrix S14: no mailbox for this one' },
      { accept: 'lines' },
    ],
    usernames: { dialog: true },
    execute: [{ group: { service: MAIL, op: 'Add', scope: 'all' }, date: 3 }],
    recap: 'By action',
    complete: true,
    customerReads: true,
    outcome: {
      status: 'Completed',
      lines: 3,
      accepted: 2,
      rejected: 1,
      people: [
        { who: { kind: 'bare', at: 12 }, services: [{ service: MAIL, status: 'Active', start: 3 }] },
        { who: { kind: 'bare', at: 13 }, services: [] },
        { who: { kind: 'bare', at: 14 }, services: [{ service: MAIL, status: 'Active', start: 3 }] },
      ],
    },
  },
  {
    id: 'S15',
    title: 'manager · one existing person · suspend · not modified · accepted by group · one row on the pre-filled date',
    asker: 'manager',
    people: [{ existing: [{ kind: 'user_active', at: 2 }] }],
    acts: [{ service: MAIL, op: 'Suspend', scope: 'all' }],
    send: 'now',
    decisions: [{ accept: 'groups' }],
    execute: [{ row: { act: { service: MAIL, op: 'Suspend', scope: 'all' }, target: { kind: 'user_active', at: 2 } } }],
    complete: true,
    customerReads: true,
    outcome: {
      status: 'Completed',
      lines: 1,
      accepted: 1,
      rejected: 0,
      people: [
        {
          who: { kind: 'user_active', at: 2 },
          services: [
            { service: MAIL, status: 'Suspended', start: -120 },
            { service: VPN, status: 'Active', start: -120 },
          ],
        },
      ],
    },
  },
  {
    id: 'S16',
    title: 'manager · suspend on several existing people, a past requested date not offered, asked for a future date · an act removed · one line refused · accepted line by line · the group button on the pre-filled date',
    asker: 'manager',
    people: [{ existing: [{ kind: 'user_active', at: 3 }, { kind: 'user_active', at: 4 }] }],
    acts: [
      { service: MAIL, op: 'Suspend', scope: 'all' },
      { service: VPN, op: 'Suspend', scope: 'all' },
    ],
    requestedDate: 4,
    refusedRequestedDate: -4,
    send: 'now',
    sentLines: 4,
    modifications: [{ changes: [{ removeAct: { service: VPN, op: 'Suspend', scope: 'all' } }] }],
    decisions: [
      {
        refuseLine: { kind: 'user_active', at: 4 },
        act: { service: MAIL, op: 'Suspend', scope: 'all' },
        reason: 'ZZE2E matrix S16: still needs the mailbox',
      },
      { accept: 'lines' },
    ],
    execute: [{ group: { service: MAIL, op: 'Suspend', scope: 'all' } }],
    complete: true,
    customerReads: true,
    outcome: {
      status: 'Completed',
      lines: 2,
      accepted: 1,
      rejected: 1,
      people: [
        {
          who: { kind: 'user_active', at: 3 },
          services: [
            { service: MAIL, status: 'Suspended', start: -120 },
            { service: VPN, status: 'Active', start: -120 },
          ],
        },
        {
          who: { kind: 'user_active', at: 4 },
          services: [
            { service: MAIL, status: 'Active', start: -120 },
            { service: VPN, status: 'Active', start: -120 },
          ],
        },
      ],
    },
  },
  {
    id: 'S17',
    title: 'requester · one existing person · resume · draft reopened from the list and sent · not offered to edit to the manager · date changed awaiting approval · approved · one row',
    asker: 'requester',
    people: [{ existing: [{ kind: 'user_suspended', at: 1 }] }],
    acts: [{ service: MAIL, op: 'Resume', scope: 'all' }],
    send: { draft: true },
    notOfferedTo: 'manager',
    modifications: [{ by: 'requester', changes: [{ date: 2 }] }],
    approval: 'approve',
    decisions: [{ accept: 'groups' }],
    execute: [{ row: { act: { service: MAIL, op: 'Resume', scope: 'all' }, target: { kind: 'user_suspended', at: 1 } } }],
    complete: true,
    customerReads: true,
    outcome: {
      status: 'Completed',
      lines: 1,
      accepted: 1,
      rejected: 0,
      people: [{ who: { kind: 'user_suspended', at: 1 }, services: [{ service: MAIL, status: 'Active', start: -120 }] }],
    },
  },
  {
    id: 'S18',
    title: 'manager · resume on several existing people · a person added · one line refused · accepted by group · Execute N ready on a changed date',
    asker: 'manager',
    people: [{ existing: [{ kind: 'user_suspended', at: 2 }, { kind: 'user_suspended', at: 3 }] }],
    acts: [{ service: MAIL, op: 'Resume', scope: 'all' }],
    send: 'now',
    sentLines: 2,
    modifications: [
      {
        changes: [
          { addPeople: { existing: [{ kind: 'user_suspended', at: 4 }] } },
          { removeAct: { service: MAIL, op: 'Resume', scope: 'all' } },
          { addAct: { service: MAIL, op: 'Resume', scope: 'all' } },
        ],
      },
    ],
    decisions: [
      { refuseLine: { kind: 'user_suspended', at: 3 }, reason: 'ZZE2E matrix S18: stays suspended' },
      { accept: 'groups' },
    ],
    execute: [{ ready: true, date: 1 }],
    complete: true,
    customerReads: true,
    outcome: {
      status: 'Completed',
      lines: 3,
      accepted: 2,
      rejected: 1,
      people: [
        { who: { kind: 'user_suspended', at: 2 }, services: [{ service: MAIL, status: 'Active', start: -120 }] },
        { who: { kind: 'user_suspended', at: 3 }, services: [{ service: MAIL, status: 'Suspended', start: -120 }] },
        { who: { kind: 'user_suspended', at: 4 }, services: [{ service: MAIL, status: 'Active', start: -120 }] },
      ],
    },
  },
  {
    id: 'S19',
    title: 'manager · one existing person · end · not modified · accepted by group · one row on the pre-filled date · recap by action',
    asker: 'manager',
    people: [{ existing: [{ kind: 'user_active', at: 5 }] }],
    acts: [{ service: MAIL, op: 'End', scope: 'all' }],
    send: 'now',
    decisions: [{ accept: 'groups' }],
    execute: [{ row: { act: { service: MAIL, op: 'End', scope: 'all' }, target: { kind: 'user_active', at: 5 } } }],
    recap: 'By action',
    complete: true,
    customerReads: true,
    outcome: {
      status: 'Completed',
      lines: 1,
      accepted: 1,
      rejected: 0,
      people: [
        {
          who: { kind: 'user_active', at: 5 },
          services: [
            { service: MAIL, status: 'Ended', start: -120, end: 0 },
            { service: VPN, status: 'Active', start: -120 },
          ],
        },
      ],
    },
  },
  {
    id: 'S20',
    title: 'manager · end on several existing people, asked for a future date · the act swapped for another · one line refused · accepted by group · the group is carried out on the future date offered',
    asker: 'manager',
    people: [{ existing: [{ kind: 'user_active', at: 6 }, { kind: 'user_active', at: 7 }] }],
    acts: [{ service: MAIL, op: 'End', scope: 'all' }],
    requestedDate: 5,
    send: 'now',
    modifications: [
      {
        changes: [
          { removeAct: { service: MAIL, op: 'End', scope: 'all' } },
          { addAct: { service: VPN, op: 'End', scope: 'all' } },
        ],
      },
    ],
    decisions: [
      { refuseLine: { kind: 'user_active', at: 7 }, reason: 'ZZE2E matrix S20: keeps the VPN' },
      { accept: 'groups' },
    ],
    execute: [{ group: { service: VPN, op: 'End', scope: 'all' } }],
    complete: true,
    customerReads: true,
    outcome: {
      status: 'Completed',
      lines: 2,
      accepted: 1,
      rejected: 1,
      people: [
        {
          who: { kind: 'user_active', at: 6 },
          services: [
            { service: MAIL, status: 'Active', start: -120 },
            { service: VPN, status: 'Ended', start: -120, end: 5 },
          ],
        },
        {
          who: { kind: 'user_active', at: 7 },
          services: [
            { service: MAIL, status: 'Active', start: -120 },
            { service: VPN, status: 'Active', start: -120 },
          ],
        },
      ],
    },
  },
  {
    id: 'S21',
    title: 'manager · several acts on one existing person: suspend one service, end another · date changed · accepted line by line · each row on its own date',
    asker: 'manager',
    people: [{ existing: [{ kind: 'user_active', at: 8 }] }],
    acts: [
      { service: MAIL, op: 'Suspend', scope: 'all' },
      { service: VPN, op: 'End', scope: 'all' },
    ],
    send: 'now',
    modifications: [{ changes: [{ date: 1 }] }],
    decisions: [{ accept: 'lines' }],
    execute: [
      { row: { act: { service: MAIL, op: 'Suspend', scope: 'all' }, target: { kind: 'user_active', at: 8 } } },
      { row: { act: { service: VPN, op: 'End', scope: 'all' }, target: { kind: 'user_active', at: 8 } }, date: 0 },
    ],
    complete: true,
    outcome: {
      status: 'Completed',
      lines: 2,
      accepted: 2,
      rejected: 0,
      people: [
        {
          who: { kind: 'user_active', at: 8 },
          services: [
            { service: MAIL, status: 'Suspended', start: -120 },
            { service: VPN, status: 'Ended', start: -120, end: 0 },
          ],
        },
      ],
    },
  },
  {
    id: 'S22',
    title: 'manager · mixed acts on mixed people · a person and an act added, then the date changed · locked once work starts · one add refused · username on its own row · left half done, come back by clicks, finished',
    asker: 'manager',
    people: [{ existing: [{ kind: 'bare', at: 15 }, { kind: 'user_active', at: 9 }, { kind: 'named', at: 1 }] }],
    acts: [
      { service: MAIL, op: 'Add', scope: { person: { kind: 'bare', at: 15 } } },
      { service: VPN, op: 'Suspend', scope: { person: { kind: 'user_active', at: 9 } } },
      { service: VPN, op: 'Add', scope: { person: { kind: 'named', at: 1 } } },
    ],
    send: 'now',
    sentLines: 3,
    modifications: [
      {
        changes: [
          { addPeople: { existing: [{ kind: 'user_suspended', at: 5 }] } },
          { addAct: { service: MAIL, op: 'End', scope: { person: { kind: 'user_suspended', at: 5 } } } },
        ],
        lines: 4,
      },
      { changes: [{ date: 2 }] },
    ],
    lockedAfterStart: true,
    decisions: [
      {
        refuseLine: { kind: 'named', at: 1 },
        act: { service: VPN, op: 'Add', scope: 'all' },
        reason: 'ZZE2E matrix S22: no VPN for this one',
      },
      { accept: 'lines' },
    ],
    usernames: { rows: [{ kind: 'bare', at: 15 }] },
    execute: [
      { row: { act: { service: MAIL, op: 'Add', scope: 'all' }, target: { kind: 'bare', at: 15 } } },
      { leaveAndReturn: true },
      { ready: true, date: 0 },
    ],
    complete: true,
    customerReads: true,
    outcome: {
      status: 'Completed',
      lines: 4,
      accepted: 3,
      rejected: 1,
      people: [
        { who: { kind: 'bare', at: 15 }, services: [{ service: MAIL, status: 'Active', start: 2 }] },
        {
          who: { kind: 'user_active', at: 9 },
          services: [
            { service: MAIL, status: 'Active', start: -120 },
            { service: VPN, status: 'Suspended', start: -120 },
          ],
        },
        { who: { kind: 'user_suspended', at: 5 }, services: [{ service: MAIL, status: 'Ended', start: -120, end: 0 }] },
        { who: { kind: 'named', at: 1 }, services: [] },
      ],
    },
  },
  {
    id: 'S23',
    title: 'manager · an existing and a future person together · the same add on both · an act added · the future person resolved to an existing one instead of created · usernames in one dialog',
    asker: 'manager',
    people: [{ existing: [{ kind: 'bare', at: 16 }] }, { future: { key: 'fu', label: 'Future Twin' } }],
    acts: [{ service: VPN, op: 'Add', scope: 'all' }],
    send: 'now',
    sentLines: 2,
    modifications: [{ changes: [{ addAct: { service: MAIL, op: 'Add', scope: { person: { kind: 'bare', at: 16 } } } }] }],
    decisions: [{ accept: 'groups' }],
    prepare: [{ person: 'fu', how: { useExisting: { kind: 'bare', at: 17 } } }],
    usernames: { dialog: true },
    execute: [{ ready: true }],
    complete: true,
    customerReads: true,
    outcome: {
      status: 'Completed',
      lines: 3,
      accepted: 3,
      rejected: 0,
      people: [
        {
          who: { kind: 'bare', at: 16 },
          services: [
            { service: MAIL, status: 'Active', start: 0 },
            { service: VPN, status: 'Active', start: 0 },
          ],
        },
        { who: { kind: 'bare', at: 17 }, services: [{ service: VPN, status: 'Active', start: 0 }] },
      ],
    },
  },
  {
    id: 'S24',
    title: 'manager · two future people in one request, one with a username, one name only · not modified · the first one created and their VPN refused · usernames in one dialog · recap by person',
    asker: 'manager',
    people: [
      {
        future: {
          key: 'a',
          label: 'First Newcomer',
          department: 'alpha',
          email: 'zze2e.mx.s24@example.invalid',
          username: 'zze2e.mx.s24',
        },
      },
      { future: { key: 'b', label: 'Second Newcomer' } },
    ],
    acts: [
      { service: MAIL, op: 'Add', scope: 'all' },
      { service: VPN, op: 'Add', scope: 'all' },
    ],
    send: 'now',
    decisions: [
      {
        refuseLine: { future: 'a' },
        act: { service: VPN, op: 'Add', scope: 'all' },
        reason: 'ZZE2E matrix S24: the first newcomer works on site',
      },
      { accept: 'lines' },
    ],
    prepare: [
      { person: 'a', how: 'create', opensOn: 'Create new' },
      { person: 'b', how: 'create', department: 'beta' },
    ],
    usernames: { dialog: true },
    execute: [{ ready: true }],
    recap: 'By person',
    complete: true,
    customerReads: true,
    outcome: {
      status: 'Completed',
      lines: 4,
      accepted: 3,
      rejected: 1,
      people: [
        {
          who: { future: 'a' },
          services: [{ service: MAIL, status: 'Active', start: 0 }],
          username: 'zze2e.mx.s24',
          department: 'alpha',
        },
        {
          who: { future: 'b' },
          services: [
            { service: MAIL, status: 'Active', start: 0 },
            { service: VPN, status: 'Active', start: 0 },
          ],
          department: 'beta',
        },
      ],
    },
  },
  {
    id: 'S25',
    title: 'manager · draft reopened, a future person with full details added, the act the new scope made stale put back for its person, an act added, then sent · asked for a future date · accepted by group · Execute N ready on the future date offered',
    asker: 'manager',
    people: [{ existing: [{ kind: 'bare', at: 18 }] }],
    acts: [{ service: MAIL, op: 'Add', scope: 'all' }],
    requestedDate: 3,
    send: {
      draft: true,
      changes: [
        {
          addPeople: {
            future: {
              key: 'dx',
              label: 'Draft Newcomer',
              department: 'alpha',
              email: 'zze2e.mx.s25@example.invalid',
              username: 'zze2e.mx.s25',
            },
          },
        },
        { removeAct: { service: MAIL, op: 'Add', scope: 'all' } },
        { addAct: { service: MAIL, op: 'Add', scope: { person: { kind: 'bare', at: 18 } } } },
        { addAct: { service: VPN, op: 'Add', scope: { person: { future: 'dx' } } } },
      ],
    },
    sentLines: 2,
    decisions: [{ accept: 'groups' }],
    prepare: [{ person: 'dx', how: 'create' }],
    usernames: { dialog: true },
    execute: [{ ready: true }],
    complete: true,
    customerReads: true,
    outcome: {
      status: 'Completed',
      lines: 2,
      accepted: 2,
      rejected: 0,
      people: [
        { who: { kind: 'bare', at: 18 }, services: [{ service: MAIL, status: 'Active', start: 3 }] },
        {
          who: { future: 'dx' },
          services: [{ service: VPN, status: 'Active', start: 3 }],
          username: 'zze2e.mx.s25',
          department: 'alpha',
        },
      ],
    },
  },
  {
    id: 'S26',
    title: 'requester · two existing people · not offered to edit to the manager · an act added awaiting approval · approved · everything refused by Nexgen: the request is Rejected',
    asker: 'requester',
    people: [{ existing: [{ kind: 'bare', at: 19 }, { kind: 'named', at: 2 }] }],
    acts: [{ service: MAIL, op: 'Add', scope: 'all' }],
    send: 'now',
    sentLines: 2,
    notOfferedTo: 'manager',
    modifications: [{ by: 'requester', changes: [{ addAct: { service: VPN, op: 'Add', scope: 'all' } }] }],
    approval: 'approve',
    decisions: [
      { refuseGroup: { service: MAIL, op: 'Add', scope: 'all' }, reason: 'ZZE2E matrix S26: no mailbox this quarter' },
      { refuseGroup: { service: VPN, op: 'Add', scope: 'all' }, reason: 'ZZE2E matrix S26: no VPN this quarter' },
      { refuseRequest: 'ZZE2E matrix S26: nothing of this can be done' },
    ],
    customerReads: true,
    outcome: {
      status: 'Rejected',
      lines: 4,
      people: [
        { who: { kind: 'bare', at: 19 }, services: [] },
        { who: { kind: 'named', at: 2 }, services: [] },
      ],
    },
  },
  {
    id: 'S27',
    title: 'manager · two adds on several existing people, no username · date changed · a username already taken is refused on its row · each group on its own changed date',
    asker: 'manager',
    people: [{ existing: [{ kind: 'bare', at: 20 }, { kind: 'bare', at: 21 }] }],
    acts: [
      { service: MAIL, op: 'Add', scope: 'all' },
      { service: VPN, op: 'Add', scope: 'all' },
    ],
    send: 'now',
    modifications: [{ changes: [{ date: 1 }] }],
    decisions: [{ accept: 'groups' }],
    usernames: { dialog: true, taken: true },
    execute: [
      { group: { service: MAIL, op: 'Add', scope: 'all' }, date: 2 },
      { group: { service: VPN, op: 'Add', scope: 'all' }, date: 5 },
    ],
    complete: true,
    outcome: {
      status: 'Completed',
      lines: 4,
      accepted: 4,
      rejected: 0,
      people: [
        {
          who: { kind: 'bare', at: 20 },
          services: [
            { service: MAIL, status: 'Active', start: 2 },
            { service: VPN, status: 'Active', start: 5 },
          ],
        },
        {
          who: { kind: 'bare', at: 21 },
          services: [
            { service: MAIL, status: 'Active', start: 2 },
            { service: VPN, status: 'Active', start: 5 },
          ],
        },
      ],
    },
  },
  {
    id: 'S28',
    title: 'manager · a future person with full details saved as draft, reopened from the list and sent · a person added · created · username on its own row · one row on a changed date',
    asker: 'manager',
    people: [
      {
        future: {
          key: 'dn',
          label: 'Draft Full',
          department: 'beta',
          email: 'zze2e.mx.s28@example.invalid',
          username: 'zze2e.mx.s28',
        },
      },
    ],
    acts: [{ service: MAIL, op: 'Add', scope: 'all' }],
    send: { draft: true },
    sentLines: 1,
    modifications: [
      {
        changes: [
          { addPeople: { existing: [{ kind: 'bare', at: 22 }] } },
          { removeAct: { service: MAIL, op: 'Add', scope: 'all' } },
          { addAct: { service: MAIL, op: 'Add', scope: 'all' } },
        ],
      },
    ],
    decisions: [{ accept: 'groups' }],
    prepare: [{ person: 'dn', how: 'create', opensOn: 'Create new' }],
    usernames: { rows: [{ kind: 'bare', at: 22 }] },
    execute: [
      { row: { act: { service: MAIL, op: 'Add', scope: 'all' }, target: { future: 'dn' } }, date: 2 },
      { row: { act: { service: MAIL, op: 'Add', scope: 'all' }, target: { kind: 'bare', at: 22 } }, date: 2 },
    ],
    complete: true,
    customerReads: true,
    outcome: {
      status: 'Completed',
      lines: 2,
      accepted: 2,
      rejected: 0,
      people: [
        {
          who: { future: 'dn' },
          services: [{ service: MAIL, status: 'Active', start: 2 }],
          username: 'zze2e.mx.s28',
          department: 'beta',
        },
        { who: { kind: 'bare', at: 22 }, services: [{ service: MAIL, status: 'Active', start: 2 }] },
      ],
    },
  },
  {
    id: 'S29',
    title: 'manager · suspend, end and resume on three people, a past requested date not offered, asked for a future date · a person and an act added, then the date changed · worked from each person\'s view, each on its own date · recap by person',
    asker: 'manager',
    people: [{ existing: [{ kind: 'user_active', at: 10 }, { kind: 'user_active', at: 11 }] }],
    acts: [
      { service: VPN, op: 'Suspend', scope: { person: { kind: 'user_active', at: 10 } } },
      { service: MAIL, op: 'End', scope: { person: { kind: 'user_active', at: 11 } } },
    ],
    requestedDate: 7,
    refusedRequestedDate: -7,
    send: 'now',
    sentLines: 2,
    modifications: [
      {
        changes: [
          { addPeople: { existing: [{ kind: 'user_suspended', at: 6 }] } },
          { addAct: { service: MAIL, op: 'Resume', scope: { person: { kind: 'user_suspended', at: 6 } } } },
        ],
        lines: 3,
      },
      { changes: [{ date: 8 }] },
    ],
    decisions: [{ accept: 'groups' }],
    execute: [
      { person: { kind: 'user_active', at: 10 } },
      {
        person: { kind: 'user_active', at: 11 },
        rows: [{ row: { act: { service: MAIL, op: 'End', scope: 'all' }, target: { kind: 'user_active', at: 11 } }, date: 0 }],
      },
      { person: { kind: 'user_suspended', at: 6 }, date: 3 },
    ],
    recap: 'By person',
    complete: true,
    customerReads: true,
    outcome: {
      status: 'Completed',
      lines: 3,
      accepted: 3,
      rejected: 0,
      people: [
        {
          who: { kind: 'user_active', at: 10 },
          services: [
            { service: MAIL, status: 'Active', start: -120 },
            { service: VPN, status: 'Suspended', start: -120 },
          ],
        },
        {
          who: { kind: 'user_active', at: 11 },
          services: [
            { service: MAIL, status: 'Ended', start: -120, end: 0 },
            { service: VPN, status: 'Active', start: -120 },
          ],
        },
        { who: { kind: 'user_suspended', at: 6 }, services: [{ service: MAIL, status: 'Active', start: -120 }] },
      ],
    },
  },
  {
    id: 'S30',
    title: 'manager · resume on several existing people, a past requested date not offered, asked for a future date · not modified · accepted line by line · each row on its own date',
    asker: 'manager',
    people: [{ existing: [{ kind: 'user_suspended', at: 7 }, { kind: 'user_suspended', at: 8 }] }],
    acts: [{ service: MAIL, op: 'Resume', scope: 'all' }],
    requestedDate: 5,
    refusedRequestedDate: -5,
    send: 'now',
    decisions: [{ accept: 'lines' }],
    execute: [
      { row: { act: { service: MAIL, op: 'Resume', scope: 'all' }, target: { kind: 'user_suspended', at: 7 } } },
      { row: { act: { service: MAIL, op: 'Resume', scope: 'all' }, target: { kind: 'user_suspended', at: 8 } }, date: 3 },
    ],
    complete: true,
    outcome: {
      status: 'Completed',
      lines: 2,
      accepted: 2,
      rejected: 0,
      people: [
        { who: { kind: 'user_suspended', at: 7 }, services: [{ service: MAIL, status: 'Active', start: -120 }] },
        { who: { kind: 'user_suspended', at: 8 }, services: [{ service: MAIL, status: 'Active', start: -120 }] },
      ],
    },
  },
  {
    id: 'S31',
    title: 'requester · a future person, name only · their details completed awaiting approval · approved · created with the username given · nothing owed · Execute N ready',
    asker: 'requester',
    people: [{ future: { key: 'rq', label: 'Requested Newcomer' } }],
    acts: [{ service: VPN, op: 'Add', scope: 'all' }],
    send: 'now',
    modifications: [
      {
        by: 'requester',
        changes: [
          {
            replaceFuture: 'rq',
            with: {
              key: 'rq',
              label: 'Requested Newcomer',
              department: 'beta',
              email: 'zze2e.mx.s31@example.invalid',
              username: 'zze2e.mx.s31',
            },
            acts: [{ service: VPN, op: 'Add', scope: 'all' }],
          },
        ],
      },
    ],
    approval: 'approve',
    decisions: [{ accept: 'groups' }],
    prepare: [{ person: 'rq', how: 'create', opensOn: 'Create new' }],
    execute: [{ ready: true }],
    complete: true,
    customerReads: true,
    outcome: {
      status: 'Completed',
      lines: 1,
      accepted: 1,
      rejected: 0,
      people: [
        {
          who: { future: 'rq' },
          services: [{ service: VPN, status: 'Active', start: 0 }],
          username: 'zze2e.mx.s31',
          department: 'beta',
        },
      ],
    },
  },
];
